### ISSUE TITLE
error when I try to run ./train_model.sh dna 0

### ISSUE THREAD

**Issue by sll513** [AllenCellModeling/pytorch_fnet#101]
loaded all the data to /data/ folder. and run ./train_model.sh dna 0, got the following error. does anyone know the reason? Thanks,

Using existing train/test split.
DEBUG: Initializing new model!
*** Model ***
fnet.nn_modules.fnet_nn_3d.Net(**{})
iter: 0
gpu: [0]

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:18<00:00, 18.49s/it]
{'buffer_size': 1, 'npatches': 1200000}
Traceback (most recent call last):
  File "train_model.py", line 147, in <module>
    main()
  File "train_model.py", line 119, in main
    args, n_remaining_iterations, validation=True
  File "train_model.py", line 22, in get_dataloader
    ds = str_to_class(args.dataset_class)(**dataset_kwargs)
  File "/local_disk0/fnet/pytorch_fnet-master/fnet/data/czidataset.py", line 13, in __init__
    super().__init__(**kwargs)
  File "/local_disk0/fnet/pytorch_fnet-master/fnet/data/fnetdataset.py", line 45, in __init__
    self.df = pd.read_csv(self.path_csv)
  File "/databricks/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/databricks/python/lib/python3.6/site-packages/pandas/io/parsers.py", line 424, in _read
    filepath_or_buffer, encoding, compression)
  File "/databricks/python/lib/python3.6/site-packages/pandas/io/common.py", line 218, in get_filepath_or_buffer
    raise ValueError(msg.format(_type=type(filepath_or_buffer)))
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

**Comment by sll513** [comment]
all data is under pytorch_fnet-master/data

3500000427_100X_20170120_F05_P27.czi
alpha_tubulin
beta_actin
csvs
desmoplakin
dic_lamin_b1
EM_low.tif
fibrillarin
lamin_b1
MBP_low.tif
membrane_caax_63x
myosin_iib
sec61_beta
st6gal1
timelapse_wt2_s2
tom20
zo1

**Comment by gregjohnso** [comment]
hi @sll513 I fixed a bug in the download script. Please re-download and make sure you are using our `release_1` branch as well.

**Comment by sll513** [comment]
Thanks. tried release_1. But get new error while running ./scripts/test_run. sh (which was fine if I used master)

+ BUFFER_SIZE=1
+ N_ITER=8
+ RUN_DIR=saved_models/TEST
+ PATH_DATASET_CSV=data/csvs/test_run.csv
+ GPU_IDS=0
+++ dirname ./scripts/test_run.sh
++ cd ./scripts
++ pwd
+ cd /local_disk0/fnet/pytorch_fnet-release_1/scripts/..
+ rm -r saved_models/TEST
rm: cannot remove 'saved_models/TEST': No such file or directory
+ python train_model.py --n_iter 8 --path_dataset_csv data/csvs/test_run.csv --path_dataset_val_csv data/csvs/test_run.csv --interval_save 6 --buffer_size 1 --path_run_dir saved_models/TEST --gpu_ids 0
Traceback (most recent call last):
  File "train_model.py", line 2, in <module>
    import fnet.data
  File "/local_disk0/fnet/pytorch_fnet-release_1/fnet/data/__init__.py", line 1, in <module>
    from fnet.data.czidataset import CziDataset
  File "/local_disk0/fnet/pytorch_fnet-release_1/fnet/data/czidataset.py", line 2, in <module>
    from fnet.data.czireader import CziReader
  File "/local_disk0/fnet/pytorch_fnet-release_1/fnet/data/czireader.py", line 1, in <module>
    import aicsimage.io as io
  File "/local_disk0/fnet/pytorch_fnet-release_1/aicsimage/io/__init__.py", line 1, in <module>
    from . import cziReader
  File "/local_disk0/fnet/pytorch_fnet-release_1/aicsimage/io/cziReader.py", line 1, in <module>
    from . import czifile
  File "/local_disk0/fnet/pytorch_fnet-release_1/aicsimage/io/czifile.py", line 119, in <module>
    from tifffile.tifffile import FileHandle, decode_lzw, lazyattr, stripnull
ImportError: cannot import name 'decode_lzw'

**Comment by gregjohnso** [comment]
@sll513 Did you use the release_1 conda environment?

**Comment by sll513** [comment]
I just installed all the needed libs on python 3.6, anaconda3.

Then download release_1.zip and unzip it.

Then I just run the test.

It was ok with master.zip before.

Thanks,

-Lingling
