### ISSUE TITLE
"ValueError" in BufferedPatchDataset

### ISSUE THREAD

**Issue by counkomol** [AllenCellModeling/pytorch_fnet#42]
Example error message:
```
Traceback (most recent call last):
  File "train_model.py", line 206, in <module>
    main()
  File "train_model.py", line 95, in main
    for data in ds_patch:
  File "/root/projects/pytorch_fnet/fnet/data/bufferedpatchdataset.py", line 61, in __getitem__
    return self.get_random_patch()
  File "/root/projects/pytorch_fnet/fnet/data/bufferedpatchdataset.py", line 81, in get_random_patch
    starts = np.array([np.random.randint(0, d-p) for d, p in zip(datum[0].size(), self.patch_size)])
  File "/root/projects/pytorch_fnet/fnet/data/bufferedpatchdataset.py", line 81, in <listcomp>
    starts = np.array([np.random.randint(0, d-p) for d, p in zip(datum[0].size(), self.patch_size)])
  File "mtrand.pyx", line 988, in mtrand.RandomState.randint
ValueError: low >= high
```

**Comment by gregjohnso** [comment]
Fixed with pull request #43
